### ISSUE TITLE
QASTRATEGY101第二个40应该是N

### ISSUE THREAD

**Issue by pchaos** [yutiansut/QASTRATEGY101#1]
def strategy001(data, N=40, mu=1):
    MP = QA.MA((data.high+data.low+data.close)/3, N)
    TR = pd.concat([abs(data.high - data.low), abs(data.high - data.close.shift(1)),
                    abs(data.low - data.close.shift(1))], axis=1).max(axis=1)
    upBand = MP + mu*QA.MA(TR, N)
    dnBand = MP + mu*QA.MA(TR, 40)
    FP = MP

上面函数,第二个40应该是N
两个地方要改

**Comment by pchaos** [comment]
另外py文件没有import QUANTAXIS as QA

**Comment by yutiansut** [comment]
get  我改下

**Comment by pchaos** [comment]
analysis.ipynb里面的40没改

干脆analysis.ipynb里面import strategy001
定义一次 总比便于维护

**Comment by yutiansut** [comment]
可以的
